### PR TITLE
Update libraries and reformat imports

### PR DESCRIPTION
**Pull request by jhorbowicz**
Since new version of nextjs was released, I think it is a good time to update some of the libraries (including react and typescript) to newest versions.

### CODE REVIEW

**Comment by bilelmoussaoui** [comment]
Thanks for the PR! before we can actually merge it, it would be nice to get the actions back to working by dropping the use of the tslint action. We should probably also migrate to eslint; do you have any preferences from linter perspective?

**Comment by jhorbowicz** [comment]
ON a regular basis, I use eslint for code smells (like variable name shadowing) and prettier to format the code. It is pretty much standard today for every react application, although I'm open of other suggestions :)

**Comment by bilelmoussaoui** [comment]
Thanks a lot for fixing the CI!

**Comment by bilelmoussaoui** [comment]
I suppose this can be merged now? it looks good to me

**Comment by jhorbowicz** [comment]
Since version 11 NextJS provides it's own plugin to ESlint, that apart from usual eslint warning provides rules that highlight common issues and mistakes while using NextJS. I think it could be good start, then we can think of adding or not prettier or any other tool that forces developers to keep consistent formatting :)

**Comment by bilelmoussaoui** [comment]
> Since version 11 NextJS provides it's own plugin to ESlint, that apart from usual eslint warning provides rules that highlight common issues and mistakes while using NextJS. I think it could be good start, then we can think of adding or not prettier or any other tool that forces developers to keep consistent formatting :)

Prettier looks good to me :)

**Comment by razzeee** [comment]
The `tslint.json` is still in the solution and we import tslint as a devDependency. A quick search seemed, like next > 11 will only ever use eslint. So it should be unused now?

**Pull request merged**
