### PR TITLE
Translations

### PR DESCRIPTION
**Pull request by razzeee**
This brings frontend translations. It's not ready, but it proves, that it's possible in different places in the application, I'll be working on replacing all strings.

There will probably be oddities, with translations being the wrong way around etc. but this will first focus on the replacing all hard coded strings.

It probably also won't have a language switcher for now. You can switch by going to a page via:
http://localhost:3000/en/apps/details/org.telegram.desktop
http://localhost:3000/de/apps/details/org.telegram.desktop

The old url still exists and defaults to english
http://localhost:3000/apps/details/org.telegram.desktop

Closes https://github.com/flathub/frontend/issues/155

### CODE REVIEW

**Comment by razzeee** [comment]
Current todos
- [ ] Move all normal strings to translations
- [ ] Figure out how to handle strings with links and other tags
- [ ] See how this affects build time
- [ ] Add complete german translations for valid testing
- [ ] Check if site map has the tranlated pages
- [ ] Translate statistics (I guess the date needs a locale)

**Comment by razzeee** [comment]
Current build seems to have finished in 23mins previously we were at 15mins. It's okayish and we can probably move along with this in the time being

**Comment by razzeee** [comment]
`yarn export` doesn't seem to work with this

```
Error: i18n support is not compatible with next export. See here for more info on deploying: https://nextjs.org/docs/deployment
```

**Comment by razzeee** [comment]
Sitemap generation seems broken, but seems to be the case in master too

**Comment by razzeee** [comment]
NVM, I just got confused, it's working fine

**Comment by razzeee** [comment]
@barthalion 
Seems like we shouldn't go the `yarn export` route, but use `yarn start` and just have it running lie that. Which needs deploy changes.

https://nextjs.org/docs/deployment#nodejs-server

**Comment by razzeee** [comment]
Otherwise, this should be good to go

**Comment by razzeee** [comment]
I would think german right now.

**Comment by barthalion** [comment]
I'm principally against displaying translated applications right now, given we don't do any vetting or requirements for language availability. I think it's just poor UX to show some descriptions in language XYZ but not FOO, and the other way for different ID.

We probably should have translations for upcoming donations/payments parts though.

**Comment by razzeee** [comment]
For clarity, this does not show any translated applications.

**Comment by barthalion** [comment]
OK, the URL scheme confused me. No complains from me then.

**Comment by razzeee** [comment]
Rebased upon master, seems to still work fine with the incremental build stuff

**Comment by razzeee** [comment]
Going to merge this, as we can always revert.

**Pull request merged**
